name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl:
          - '5.16'
          - 'latest'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Install dependencies
        run: cpanm --notest --installdeps .

      - name: Build and test
        run: |
          perl Makefile.PL
          make test
